# Generated by Django 2.2.7 on 2019-11-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='tddate',
            field=models.DateField(null=True),
        ),
    ]
