# Generated by Django 2.2.7 on 2019-11-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermatch', '0003_auto_20191128_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
